# Getting Financial Data - Pandas Datareader

### Introduction:

This time you will get data from a website.


### Step 1. Import the necessary libraries

In [1]:
import pandas as pd

### Step 2. Create your time range (start and end variables). The start date should be 01/01/2015 and the end should today (whatever your today is).

In [6]:
date = pd.date_range(start='2026-01-01', end=pd.Timestamp.today(), freq='D')

### Step 3. Get an API key for one of the APIs that are supported by Pandas Datareader, preferably for AlphaVantage.

If you do not have an API key for any of the supported APIs, it is easiest to get one for [AlphaVantage](https://www.alphavantage.co/support/#api-key). (Note that the API key is shown directly after the signup. You do *not* receive it via e-mail.)

(For a full list of the APIs that are supported by Pandas Datareader, [see here](https://pydata.github.io/pandas-datareader/readers/index.html). As the APIs are provided by third parties, this list may change.)

In [14]:
import yfinance as yf
import pandas as pd

df_apple = yf.download(
    'AAPL',
    start='2015-01-01',
    end=pd.Timestamp.today()
)

print(df_apple.head())

/tmp/ipykernel_11687/2390625415.py:4: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df_apple = yf.download(
[*********************100%***********************]  1 of 1 completed

Price           Close       High        Low       Open     Volume
Ticker           AAPL       AAPL       AAPL       AAPL       AAPL
Date
2015-01-02  24.214890  24.682222  23.776350  24.671147  212818400
2015-01-05  23.532717  24.064280  23.346671  23.984545  257142000
2015-01-06  23.534933  23.794069  23.173912  23.596948  263188400
2015-01-07  23.864946  23.964614  23.632387  23.743129  160423600
2015-01-08  24.781889  24.839475  24.075353  24.192741  237458000

### Step 4. Use Pandas Datarader to read the daily time series for the Apple stock (ticker symbol AAPL) between 01/01/2015 and today, assign it to df_apple and print it.

In [15]:
import yfinance as yf
import pandas as pd

df_apple = yf.download(
    'AAPL',
    start='2015-01-01',
    end=pd.Timestamp.today()
)

print(df_apple)

/tmp/ipykernel_11687/668540960.py:4: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df_apple = yf.download(
[*********************100%***********************]  1 of 1 completed

Price            Close        High         Low        Open     Volume
Ticker            AAPL        AAPL        AAPL        AAPL       AAPL
Date
2015-01-02   24.214895   24.682228   23.776355   24.671153  212818400
2015-01-05   23.532713   24.064276   23.346667   23.984541  257142000
2015-01-06   23.534941   23.794077   23.173920   23.596956  263188400
2015-01-07   23.864946   23.964614   23.632387   23.743129  160423600
2015-01-08   24.781895   24.839481   24.075359   24.192747  237458000
...                ...         ...         ...         ...        ...
2026-04-14  258.829987  261.929993  257.190002  259.250000   48370700
2026-04-15  266.429993  266.559998  257.809998  258.160004   49913500
2026-04-16  263.399994  267.160004  261.269989  266.799988   43323100
2026-04-17  270.230011  272.299988  266.720001  266.959991   61314800
2026-04-20  273.049988  274.274994  270.290009  270.329987   34667241

[2840 rows x 5 columns]

### Step 5. Add a new column "stock" to the dataframe and add the ticker symbol

In [16]:
df_apple['stock'] = 'AAPL'

df_apple.head()

Price           Close       High        Low       Open     Volume stock
Ticker           AAPL       AAPL       AAPL       AAPL       AAPL
Date
2015-01-02  24.214895  24.682228  23.776355  24.671153  212818400  AAPL
2015-01-05  23.532713  24.064276  23.346667  23.984541  257142000  AAPL
2015-01-06  23.534941  23.794077  23.173920  23.596956  263188400  AAPL
2015-01-07  23.864946  23.964614  23.632387  23.743129  160423600  AAPL
2015-01-08  24.781895  24.839481  24.075359  24.192747  237458000  AAPL

### Step 6. Repeat the two previous steps for a few other stocks, always creating a new dataframe: Tesla, IBM and Microsoft. (Ticker symbols TSLA, IBM and MSFT.)

In [17]:
import yfinance as yf
import pandas as pd

df_tsla = yf.download('TSLA', start='2015-01-01', end=pd.Timestamp.today())
df_tsla['stock'] = 'TSLA'

df_ibm = yf.download('IBM', start='2015-01-01', end=pd.Timestamp.today())
df_ibm['stock'] = 'IBM'

df_msft = yf.download('MSFT', start='2015-01-01', end=pd.Timestamp.today())
df_msft['stock'] = 'MSFT'

print(df_tsla.head())
print(df_ibm.head())
print(df_msft.head())

/tmp/ipykernel_11687/2472879103.py:4: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df_tsla = yf.download('TSLA', start='2015-01-01', end=pd.Timestamp.today())
[*********************100%***********************]  1 of 1 completed
/tmp/ipykernel_11687/2472879103.py:7: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df_ibm = yf.download('IBM', start='2015-01-01', end=pd.Timestamp.today())
[*********************100%***********************]  1 of 1 completed
/tmp/ipykernel_11687/2472879103.py:10: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df_msft = yf.download('MSFT', start='2015-01-01', end=pd.Timestamp.today())
[*********************100%***********************]  1 of 1 completed

Price           Close       High        Low       Open    Volume stock
Ticker           TSLA       TSLA       TSLA       TSLA      TSLA
Date
2015-01-02  14.620667  14.883333  14.217333  14.858000  71466000  TSLA
2015-01-05  14.006000  14.433333  13.810667  14.303333  80527500  TSLA
2015-01-06  14.085333  14.280000  13.614000  14.004000  93928500  TSLA
2015-01-07  14.063333  14.318667  13.985333  14.223333  44526000  TSLA
2015-01-08  14.041333  14.253333  14.000667  14.187333  51637500  TSLA
Price           Close       High        Low       Open   Volume stock
Ticker            IBM        IBM        IBM        IBM      IBM
Date
2015-01-02  97.566765  98.319322  96.928603  97.115238  5779673   IBM
2015-01-05  96.031578  97.091171  95.838927  97.091171  5104898   IBM
2015-01-06  93.960548  96.302491  93.418717  96.127895  6429448   IBM
2015-01-07  93.346474  94.640863  92.732392  94.640863  4918083   IBM
2015-01-08  95.375351  95.748612  93.647491  94.062897  4431693   IBM
Price           Close       High        Low       Open    Volume stock
Ticker           MSFT       MSFT       MSFT       MSFT      MSFT
Date
2015-01-02  39.767689  40.328995  39.580589  39.682644  27913900  MSFT
2015-01-05  39.402004  39.742188  39.333966  39.436020  39673900  MSFT
2015-01-06  38.823677  39.759186  38.730126  39.444515  36447900  MSFT
2015-01-07  39.316940  39.512547  38.687599  39.104324  29114100  MSFT
2015-01-08  40.473564  40.609638  39.733662  39.759175  29645200  MSFT

### Step 7. Combine the four separate dataFrames into one combined dataFrame df that holds the information for all four stocks

In [18]:
import pandas as pd

df = pd.concat([df_apple, df_tsla, df_ibm, df_msft])

df.head()

Price,Close,High,Low,Open,Volume,stock,Close,High,Low,Open,...,Close,High,Low,Open,Volume,Close,High,Low,Open,Volume
Ticker,AAPL,AAPL,AAPL,AAPL,AAPL,,TSLA,TSLA,TSLA,TSLA,...,IBM,IBM,IBM,IBM,IBM,MSFT,MSFT,MSFT,MSFT,MSFT
Date,,,,,,,,,,,,,,,,,,,,,
2015-01-02,24.214895,24.682228,23.776355,24.671153,212818400.0,AAPL,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2015-01-05,23.532713,24.064276,23.346667,23.984541,257142000.0,AAPL,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2015-01-06,23.534941,23.794077,23.173920,23.596956,263188400.0,AAPL,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2015-01-07,23.864946,23.964614,23.632387,23.743129,160423600.0,AAPL,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2015-01-08,24.781895,24.839481,24.075359,24.192747,237458000.0,AAPL,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Step 8. Shift the stock column into the index (making it a multi-level index consisting of the ticker symbol and the date).

In [19]:
df = df.set_index('stock', append=True)

df.head()

,Price,Close,High,Low,Open,Volume,Close,High,Low,Open,Volume,Close,High,Low,Open,Volume,Close,High,Low,Open,Volume
,Ticker,AAPL,AAPL,AAPL,AAPL,AAPL,TSLA,TSLA,TSLA,TSLA,TSLA,IBM,IBM,IBM,IBM,IBM,MSFT,MSFT,MSFT,MSFT,MSFT
Date,stock,,,,,,,,,,,,,,,,,,,,
2015-01-02,AAPL,24.214895,24.682228,23.776355,24.671153,212818400.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2015-01-05,AAPL,23.532713,24.064276,23.346667,23.984541,257142000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2015-01-06,AAPL,23.534941,23.794077,23.173920,23.596956,263188400.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2015-01-07,AAPL,23.864946,23.964614,23.632387,23.743129,160423600.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2015-01-08,AAPL,24.781895,24.839481,24.075359,24.192747,237458000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Step 7. Create a dataFrame called vol, with the volume values.

In [20]:
vol = df[['Volume']]

vol.head()

Price                  Volume
Ticker                   AAPL TSLA IBM MSFT
Date       stock
2015-01-02 AAPL   212818400.0  NaN NaN  NaN
2015-01-05 AAPL   257142000.0  NaN NaN  NaN
2015-01-06 AAPL   263188400.0  NaN NaN  NaN
2015-01-07 AAPL   160423600.0  NaN NaN  NaN
2015-01-08 AAPL   237458000.0  NaN NaN  NaN

### Step 8. Aggregate the data of volume to weekly.
Hint: Be careful to not sum data from the same week of 2015 and other years.

In [22]:
df_reset = df.reset_index()

In [23]:
df_reset['Date'] = pd.to_datetime(df_reset['Date'])

In [24]:
df_reset = df_reset.set_index('Date')

In [25]:
vol = df_reset[['Volume']]

vol_weekly = vol.resample('W').sum()

vol_weekly.head()

Price             Volume
Ticker              AAPL         TSLA         IBM         MSFT
Date
2015-01-04  2.128184e+08   71466000.0   5779673.0   27913900.0
2015-01-11  1.133010e+09  340644000.0  25578884.0  158825300.0
2015-01-18  1.216906e+09  461988000.0  24329751.0  157088200.0
2015-01-25  7.949480e+08  243175500.0  32682062.0  137352600.0
2015-02-01  1.863371e+09  235803000.0  34442689.0  437786800.0

### Step 9. Find all the volume traded in the year of 2015

In [26]:
df_2015 = df.reset_index()
df_2015['Date'] = pd.to_datetime(df_2015['Date'])

volume_2015 = df_2015[df_2015['Date'].dt.year == 2015]['Volume'].sum()

print(volume_2015)

Ticker
AAPL    5.226420e+10
TSLA    1.632327e+10
IBM     1.156439e+09
MSFT    9.059456e+09
dtype: float64