# Housing Market

### Introduction:

This time we will create our own dataset with fictional numbers to describe a house market. As we are going to create random data don't try to reason of the numbers.

### Step 1. Import the necessary libraries

In [3]:
import pandas as pd
import numpy as np

### Step 2. Create 3 differents Series, each of length 100, as follows:
1. The first a random number from 1 to 4
2. The second a random number from 1 to 3
3. The third a random number from 10,000 to 30,000

In [4]:
first=pd.Series(np.random.randint(1,5,100))
second=pd.Series(np.random.randint(1,4,100))
third=pd.Series(np.random.randint(10000,30000,100))

### Step 3. Let's create a DataFrame by joinning the Series by column

In [5]:
df = pd.concat([first, second, third], axis=1)

In [7]:
df.columns=['first','second','third']

In [8]:
df

    first  second  third
0       2       1  19578
1       2       3  22445
2       2       3  11391
3       3       2  27253
4       4       1  28746
..    ...     ...    ...
95      1       3  27771
96      1       3  19801
97      3       1  12055
98      2       3  22143
99      2       1  28380

[100 rows x 3 columns]

### Step 4. Change the name of the columns to bedrs, bathrs, price_sqr_meter

In [9]:
df.columns=['bedrs','bathrs','price_sqr_meter']

### Step 5. Create a one column DataFrame with the values of the 3 Series and assign it to 'bigcolumn'

In [10]:
df1=pd.concat([first, second, third], axis=0)

### Step 6. Oops, it seems it is going only until index 99. Is it true?

In [11]:
df1=df1.reset_index()

### Step 7. Reindex the DataFrame so it goes from 0 to 299

In [12]:
df1

     index      0
0        0      2
1        1      2
2        2      2
3        3      3
4        4      4
..     ...    ...
295     95  27771
296     96  19801
297     97  12055
298     98  22143
299     99  28380

[300 rows x 2 columns]