# Ex -

### Introduction:

This time you will create a data

Special thanks to: https://github.com/justmarkham for sharing the dataset and materials.

### Step 1. Import the necessary libraries

In [1]:
import pandas as pd

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv).

In [2]:
df=pd.read_csv('https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv',sep='\t')

### Step 3. Assign it to a variable called

In [3]:
mydat=df
mydat.head(5)

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98

### Step 4.

In [5]:
mydat.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4622 entries, 0 to 4621
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   order_id            4622 non-null   int64
 1   quantity            4622 non-null   int64
 2   item_name           4622 non-null   object
 3   choice_description  3376 non-null   object
 4   item_price          4622 non-null   object
dtypes: int64(2), object(3)
memory usage: 180.7+ KB

### Step 5.

In [6]:
mydat.isna().sum()

order_id                 0
quantity                 0
item_name                0
choice_description    1246
item_price               0
dtype: int64

### Step 6.

In [10]:
mydat.iloc[0:5]

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98

### Step 7.

In [11]:
mydat[['item_name', 'item_price']].head()

                               item_name item_price
0           Chips and Fresh Tomato Salsa     $2.39
1                                   Izze     $3.39
2                       Nantucket Nectar     $3.39
3  Chips and Tomatillo-Green Chili Salsa     $2.39
4                           Chicken Bowl    $16.98

### Step 8.

In [12]:
mydat[mydat['quantity'] > 1].head()

,order_id,quantity,item_name,choice_description,item_price
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
18,9,2,Canned Soda,[Sprite],$2.18
51,23,2,Canned Soda,[Mountain Dew],$2.18
135,60,2,Chicken Salad Bowl,"[Tomatillo Green Chili Salsa, [Sour Cream, Che...",$22.50
148,67,2,Steak Burrito,"[Tomatillo-Red Chili Salsa (Hot), [Rice, Chees...",$17.98

### Step 9.

In [13]:
mydat['item_name'].nunique()

50

### Step 10.

In [14]:
mydat['item_name'].mode()[0]

'Chicken Bowl'

### Step 11.

In [15]:
mydat['quantity'].sum()

np.int64(4972)

### Step 12. Question: What is the most expensive item ordered in the 'item_name' column?

In [16]:
mydat['item_price'] = mydat['item_price'].str.replace('$', '').astype(float)

most_expensive_item = mydat.loc[mydat['item_price'].idxmax()]
f"The most expensive item ordered is '{most_expensive_item['item_name']}' with a price of ${most_expensive_item['item_price']:.2f}."

"The most expensive item ordered is 'Chips and Fresh Tomato Salsa' with a price of $44.25."

In [ ]:
# First, clean the 'item_price' column by removing the dollar sign and converting to a float.
mydat['item_price'] = mydat['item_price'].str.replace('$', '').astype(float)

# Then, find the item with the maximum price.
most_expensive_item = mydat.loc[mydat['item_price'].idxmax()]

print(f"The most expensive item ordered is '{most_expensive_item['item_name']}' with a price of ${most_expensive_item['item_price']:.2f}.")

### Step 13. Question: How many items cost more than $10?

In [17]:
items_over_10 = mydat[mydat['item_price'] > 10.0]
num_items_over_10 = len(items_over_10)
f"There are {num_items_over_10} items that cost more than $10."

'There are 1130 items that cost more than $10.'

In [ ]:
items_over_10 = mydat[mydat['item_price'] > 10.0]
num_items_over_10 = len(items_over_10)

print(f"There are {num_items_over_10} items that cost more than $10.")

### Step 14. Question: What is the average price per item?

In [18]:
average_price = mydat['item_price'].mean()
f"The average price per item is ${average_price:.2f}."

'The average price per item is $7.46.'

In [ ]:
average_price = mydat['item_price'].mean()

print(f"The average price per item is ${average_price:.2f}.")

### Step 15. Question: How many different items are in each order?

In [19]:
items_per_order = mydat.groupby('order_id')['item_name'].nunique()
items_per_order.head()

order_id
1    4
2    1
3    2
4    2
5    2
Name: item_name, dtype: int64

In [ ]:
items_per_order = mydat.groupby('order_id')['item_name'].nunique()

print("Number of different items in each order (first 5 rows):")
print(items_per_order.head())

### Step 16. Question: What are the top 5 most commonly ordered items, and how many times were they ordered?

In [20]:
top_5_items = mydat['item_name'].value_counts().head(5)
top_5_items

item_name
Chicken Bowl           726
Chicken Burrito        553
Chips and Guacamole    479
Steak Burrito          368
Canned Soft Drink      301
Name: count, dtype: int64