# Iris

### Introduction:

This exercise may seem a little bit strange, but keep doing it.

### Step 1. Import the necessary libraries

In [3]:
import pandas as pd

### Step 2. Import the dataset from this [address](https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data).

In [4]:
df=pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data')

### Step 3. Assign it to a variable called iris

In [5]:
iris=df
iris

     5.1  3.5  1.4  0.2     Iris-setosa
0    4.9  3.0  1.4  0.2     Iris-setosa
1    4.7  3.2  1.3  0.2     Iris-setosa
2    4.6  3.1  1.5  0.2     Iris-setosa
3    5.0  3.6  1.4  0.2     Iris-setosa
4    5.4  3.9  1.7  0.4     Iris-setosa
..   ...  ...  ...  ...             ...
144  6.7  3.0  5.2  2.3  Iris-virginica
145  6.3  2.5  5.0  1.9  Iris-virginica
146  6.5  3.0  5.2  2.0  Iris-virginica
147  6.2  3.4  5.4  2.3  Iris-virginica
148  5.9  3.0  5.1  1.8  Iris-virginica

[149 rows x 5 columns]

### Step 4. Create columns for the dataset

In [ ]:
# 1. sepal_length (in cm)
# 2. sepal_width (in cm)
# 3. petal_length (in cm)
# 4. petal_width (in cm)
# 5. class

In [6]:
iris.columns=['sepal_length','sepal_width','petal_length','petal_width','class']
iris

     sepal_length  sepal_width  petal_length  petal_width           class
0             4.9          3.0           1.4          0.2     Iris-setosa
1             4.7          3.2           1.3          0.2     Iris-setosa
2             4.6          3.1           1.5          0.2     Iris-setosa
3             5.0          3.6           1.4          0.2     Iris-setosa
4             5.4          3.9           1.7          0.4     Iris-setosa
..            ...          ...           ...          ...             ...
144           6.7          3.0           5.2          2.3  Iris-virginica
145           6.3          2.5           5.0          1.9  Iris-virginica
146           6.5          3.0           5.2          2.0  Iris-virginica
147           6.2          3.4           5.4          2.3  Iris-virginica
148           5.9          3.0           5.1          1.8  Iris-virginica

[149 rows x 5 columns]

### Step 5.  Is there any missing value in the dataframe?

In [7]:
iris.isnull().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
class           0
dtype: int64

### Step 6.  Lets set the values of the rows 10 to 29 of the column 'petal_length' to NaN

In [8]:
iris.loc[10:29,'petal_length']=pd.NA

### Step 7. Good, now lets substitute the NaN values to 1.0

In [9]:
iris.fillna(1.0,inplace=True)
iris

     sepal_length  sepal_width  petal_length  petal_width           class
0             4.9          3.0           1.4          0.2     Iris-setosa
1             4.7          3.2           1.3          0.2     Iris-setosa
2             4.6          3.1           1.5          0.2     Iris-setosa
3             5.0          3.6           1.4          0.2     Iris-setosa
4             5.4          3.9           1.7          0.4     Iris-setosa
..            ...          ...           ...          ...             ...
144           6.7          3.0           5.2          2.3  Iris-virginica
145           6.3          2.5           5.0          1.9  Iris-virginica
146           6.5          3.0           5.2          2.0  Iris-virginica
147           6.2          3.4           5.4          2.3  Iris-virginica
148           5.9          3.0           5.1          1.8  Iris-virginica

[149 rows x 5 columns]

### Step 8. Now let's delete the column class

In [10]:
iris.drop('class',axis=1,inplace=True)
iris

     sepal_length  sepal_width  petal_length  petal_width
0             4.9          3.0           1.4          0.2
1             4.7          3.2           1.3          0.2
2             4.6          3.1           1.5          0.2
3             5.0          3.6           1.4          0.2
4             5.4          3.9           1.7          0.4
..            ...          ...           ...          ...
144           6.7          3.0           5.2          2.3
145           6.3          2.5           5.0          1.9
146           6.5          3.0           5.2          2.0
147           6.2          3.4           5.4          2.3
148           5.9          3.0           5.1          1.8

[149 rows x 4 columns]

### Step 9.  Set the first 3 rows as NaN

In [11]:
iris.loc[0:2]=pd.NA
iris

     sepal_length  sepal_width  petal_length  petal_width
0             NaN          NaN           NaN          NaN
1             NaN          NaN           NaN          NaN
2             NaN          NaN           NaN          NaN
3             5.0          3.6           1.4          0.2
4             5.4          3.9           1.7          0.4
..            ...          ...           ...          ...
144           6.7          3.0           5.2          2.3
145           6.3          2.5           5.0          1.9
146           6.5          3.0           5.2          2.0
147           6.2          3.4           5.4          2.3
148           5.9          3.0           5.1          1.8

[149 rows x 4 columns]

### Step 10.  Delete the rows that have NaN

In [12]:
iris.dropna(inplace=True)
iris

     sepal_length  sepal_width  petal_length  petal_width
3             5.0          3.6           1.4          0.2
4             5.4          3.9           1.7          0.4
5             4.6          3.4           1.4          0.3
6             5.0          3.4           1.5          0.2
7             4.4          2.9           1.4          0.2
..            ...          ...           ...          ...
144           6.7          3.0           5.2          2.3
145           6.3          2.5           5.0          1.9
146           6.5          3.0           5.2          2.0
147           6.2          3.4           5.4          2.3
148           5.9          3.0           5.1          1.8

[146 rows x 4 columns]

### Step 11. Reset the index so it begins with 0 again

In [13]:
iris.reset_index(drop=True,inplace=True)
iris

     sepal_length  sepal_width  petal_length  petal_width
0             5.0          3.6           1.4          0.2
1             5.4          3.9           1.7          0.4
2             4.6          3.4           1.4          0.3
3             5.0          3.4           1.5          0.2
4             4.4          2.9           1.4          0.2
..            ...          ...           ...          ...
141           6.7          3.0           5.2          2.3
142           6.3          2.5           5.0          1.9
143           6.5          3.0           5.2          2.0
144           6.2          3.4           5.4          2.3
145           5.9          3.0           5.1          1.8

[146 rows x 4 columns]

### BONUS: Create your own question and answer it.