# Ex1 - Filtering and Sorting Data

This time we are going to pull data directly from the internet.
Special thanks to: https://github.com/justmarkham for sharing the dataset and materials.

### Step 1. Import the necessary libraries

In [3]:
import pandas as pd

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv).

In [6]:
df=pd.read_csv('https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv',sep='\t')

### Step 3. Assign it to a variable called chipo.

In [7]:
chipo=df

In [8]:
chipo.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4622 entries, 0 to 4621
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   order_id            4622 non-null   int64
 1   quantity            4622 non-null   int64
 2   item_name           4622 non-null   object
 3   choice_description  3376 non-null   object
 4   item_price          4622 non-null   object
dtypes: int64(2), object(3)
memory usage: 180.7+ KB

### Step 4. How many products cost more than $10.00?

In [10]:
chipo["item_price"].head()

0     $2.39
1     $3.39
2     $3.39
3     $2.39
4    $16.98
Name: item_price, dtype: object

In [19]:
chipo["item_price"]=chipo["item_price"].str.replace('$','').astype(float)

In [21]:
chipo["item_price"].head()

0     2.39
1     3.39
2     3.39
3     2.39
4    16.98
Name: item_price, dtype: float64

In [27]:
print((chipo['item_price']>10).sum())

1130

### Step 5. What is the price of each item?
###### print a data frame with only two columns item_name and item_price

In [29]:
chipo[['item_name','item_price']]

                                  item_name  item_price
0              Chips and Fresh Tomato Salsa        2.39
1                                      Izze        3.39
2                          Nantucket Nectar        3.39
3     Chips and Tomatillo-Green Chili Salsa        2.39
4                              Chicken Bowl       16.98
...                                     ...         ...
4617                          Steak Burrito       11.75
4618                          Steak Burrito       11.75
4619                     Chicken Salad Bowl       11.25
4620                     Chicken Salad Bowl        8.75
4621                     Chicken Salad Bowl        8.75

[4622 rows x 2 columns]

### Step 6. Sort by the name of the item

In [31]:
chipo[['item_name','item_price']].sort_values('item_name')

              item_name  item_price
3389  6 Pack Soft Drink       12.98
341   6 Pack Soft Drink        6.49
1849  6 Pack Soft Drink        6.49
1860  6 Pack Soft Drink        6.49
2713  6 Pack Soft Drink        6.49
...                 ...         ...
2384  Veggie Soft Tacos        8.75
781   Veggie Soft Tacos        8.75
2851  Veggie Soft Tacos        8.49
1699  Veggie Soft Tacos       11.25
1395  Veggie Soft Tacos        8.49

[4622 rows x 2 columns]

### Step 7. What was the quantity of the most expensive item ordered?

In [39]:
print(chipo.sort_values(['item_price'],ascending=False).head(1)['quantity'])

3598    15
Name: quantity, dtype: int64

### Step 8. How many times was a Veggie Salad Bowl ordered?

In [57]:
chipo['item_name'].value_counts()['Veggie Salad Bowl']

np.int64(18)

### Step 9. How many times did someone order more than one Canned Soda?

In [68]:
(chipo[chipo['item_name'] == "Canned Soda"]['quantity'] > 1).sum()

np.int64(20)